/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AliasNewRequest { 
    /**
     * Alias name
     */
    aliasname: string;
    /**
     * alias public profile data, 256 characters max.
     */
    publicvalue: string;
    /**
     * 0 for none, 1 for accepting certificate transfers, 2 for accepting asset transfers and 3 for all. Default is 3.
     */
    accept_transfers_flags: number;
    /**
     * Epoch time when to expire alias. It is exponentially more expensive per year, calculation is FEERATE*(2.88^years). FEERATE is the dynamic satoshi per byte fee set in the rate peg alias used for this alias. Defaults to 1 hour.
     */
    expire_timestamp: number;
    /**
     * Address for this alias.
     */
    address: string;
    /**
     * Encrypted private key used for encryption decryption of private data related to this alias. Should be encrypted to publickey.
     */
    encryption_privatekey: string;
    /**
     * Public key used for encryption decryption of private data related to this alias.
     */
    encryption_publickey: string;
    /**
     * Witness alias name that will sign for web-of-trust notarization of this transaction.
     */
    witness: string;
}
