/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AliasPayRequest { 
    /**
     * Alias to pay from
     */
    aliasfrom: string;
    /**
     * A stringified JSON object with aliases and amounts. { \"address\":amount, ... } (numeric or string) The syscoin alias is the key, the numeric amount (can be string) in SYS is the value.
     */
    amounts: string;
    /**
     * Set to true to use InstantSend to send this transaction or false otherwise.
     */
    instantsend?: boolean;
    /**
     * Set to true to subtract fee from amount or false otherwise.
     */
    subtractfeefromamount?: string;
}
