/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AssetUpdateRequest { 
    /**
     * Asset name.
     */
    asset?: string;
    /**
     * Public data, 512 characters max.
     */
    _public?: string;
    /**
     * Set to assets
     */
    category?: string;
    /**
     * New supply of asset. Can mint more supply up to total_supply amount or if max_supply is -1 then minting is uncapped.
     */
    supply?: number;
    /**
     * The annual interest rate if any. Money supply is still capped to total supply. Should be between 0 and 1 and represents a percentage divided by 100. Can only set if this asset allows adjustment of interest rate.
     */
    interest_rate?: number;
    /**
     * Witness alias name that will sign for web-of-trust notarization of this transaction.
     */
    witness?: string;
}
