/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ByteMessageInfo { 
    addr: number;
    block?: number;
    getaddr?: number;
    getdata?: number;
    getheaders: number;
    headers: number;
    inv: number;
    ping: number;
    pong: number;
    sendheaders: number;
    tx?: number;
    verack: number;
    version: number;
}
