/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EscrowBidResponse { 
    _id?: string;
    offer?: string;
    escrow?: string;
    height?: number;
    bidder?: string;
    bid_in_offer_currency_per_unit?: number;
    bid_in_payment_option_per_unit?: number;
    witness?: string;
    status?: string;
}
