/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ImportPrivKeyRequest { 
    /**
     * The private key (see dumpprivkey)
     */
    syscoinprivkey: string;
    /**
     * An optional label
     */
    label?: string;
    /**
     * Rescan the wallet for transactions
     */
    rescan?: boolean;
}
