/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InstantSendToAddressRequest { 
    /**
     * (string, required) The syscoin address to send to.
     */
    syscoinaddress: string;
    /**
     * (numeric, required) The amount in sys to send. eg 0.1
     */
    amount: number;
    /**
     * (string, optional) A comment used to store what the transaction is for.
     */
    comment?: string;
    /**
     * (string, optional) A comment to store the name of the person or organization to which you're sending the transaction. This is not part of the transaction, just kept in your wallet.
     */
    comment_to?: string;
    /**
     * The fee will be deducted from the amount being sent.
     */
    subtractfeefromamount?: boolean;
}
