/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MessageNewRequest { 
    /**
     * Subject of message.
     */
    subject: string;
    /**
     * Alias to send message from.
     */
    fromalias: string;
    /**
     * Alias to send message to.
     */
    toalias: string;
    /**
     * Message encrypted to from alias.
     */
    frommessage: string;
    /**
     * Message encrypted to sending alias.
     */
    tomessage: string;
}
