/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MoveRequest { 
    /**
     * The name of the account to move funds from. May be the default account using \"\".
     */
    fromaccount: string;
    /**
     * The name of the account to move funds to. May be the default account using \"\".
     */
    toaccount: string;
    /**
     * Quantity of SYS to move between accounts.
     */
    amount: number;
    /**
     * Only use funds with at least this many confirmations.
     */
    minconf?: string;
    /**
     * An optional comment, stored in the wallet only.
     */
    comment?: string;
}
