/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NetworkInfoDetails } from './networkInfoDetails';


export interface NetworkInfo { 
    version?: number;
    subversion?: string;
    protocolversion?: number;
    localservices?: string;
    localrelay?: boolean;
    timeoffset?: number;
    connections?: number;
    networks?: Array<NetworkInfoDetails>;
    relayfee?: number;
    localaddresses?: Array<string>;
    warnings?: string;
}
