/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OfferUpdateInput { 
    alias?: string;
    guid?: string;
    category?: string;
    title?: string;
    quantity?: number;
    price?: number;
    description?: string;
    currency?: string;
    _private?: boolean;
    cert_guid?: string;
    commission?: number;
    payment_options?: string;
    offer_type?: string;
    auction_expires?: number;
    auction_reserve?: number;
    auction_require_witness?: boolean;
    auction_deposit?: number;
    witness?: string;
}
