/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OfferAddWhitelistRequest { 
    /**
     * offer guid that you are adding to
     */
    offerguid: string;
    /**
     * alias guid representing an alias that you want to add to the affiliate list
     */
    aliasguid: string;
    /**
     * Percentage of discount given to affiliate for this offer. 0 to 99.
     */
    discountPercentage?: number;
}
