/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Offer { 
    _id: string;
    cert?: string;
    txid?: string;
    expires_on?: number;
    expired?: boolean;
    height?: number;
    category?: string;
    title?: string;
    currency?: string;
    price?: number;
    commission?: number;
    offerlink_guid?: string;
    offerlink_seller?: string;
    paymentoptions?: string;
    offer_units?: number;
    quantity?: number;
    _private?: boolean;
    description?: string;
    alias?: string;
    address?: string;
    offertype?: string;
    auction_expires_on?: number;
    auction_reserve_price?: number;
    auction_require_witness?: boolean;
    auction_deposit?: number;
}
