/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UnspentListEntry { 
    /**
     * The transaction id
     */
    txid?: string;
    /**
     * The vout value
     */
    vout?: number;
    /**
     * The syscoin address
     */
    address?: string;
    /**
     * DEPRECATED. The associated account, or \"\" for the default account
     */
    account?: string;
    /**
     * The script key
     */
    scriptPubKey?: string;
    /**
     * The transaction amount in SYS
     */
    amount?: number;
    /**
     * The number of confirmations
     */
    confirmations?: number;
    /**
     * The number of PS round
     */
    ps_rounds?: number;
    /**
     * Whether we have the private keys to spend this output
     */
    spendable?: boolean;
    /**
     * Whether we know how to spend this output, ignoring the lack of keys
     */
    solvable?: boolean;
}
