/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ValidateAddressResponse { 
    /**
     * If the address is valid or not. If not, this is the only property returned.
     */
    isvalid?: boolean;
    /**
     * The syscoin address validated
     */
    address?: string;
    /**
     * If the address is yours or not
     */
    ismine?: boolean;
    /**
     * If the address is watchonly
     */
    iswatchonly?: boolean;
    /**
     * If the key is a script
     */
    isscript?: boolean;
    /**
     * The hex value of the raw public key
     */
    pubkey?: string;
    /**
     * If the address is compressed
     */
    iscompressed?: boolean;
    /**
     * DEPRECATED. The account associated with the address, \"\" is the default account
     */
    account?: string;
}
