/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface VoteRawRequest { 
    masternode_tx_hash: string;
    masternode_tx_index: number;
    governance_hash: string;
    vote_signal: number;
    vote_outcome: string;
    time: number;
    vote_sig: string;
}
